package hospital_services_application;

import javax.swing.*;
import java.awt.*;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Hospital_Services_Application_facade extends javax.swing.JFrame {
    private ImageIcon image;
    private JLabel lablel;
    private static ArrayList DB;
    
    public Hospital_Services_Application_facade() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(222, 222, 152));

        jPanel1.setBackground(new java.awt.Color(223, 177, 177));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Welcome To Our Hospital");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Your are in good hands!");

        jButton1.setText("Notifications (Command)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Change Language (Adapter)");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("(Façade)");

        jButton3.setText("Online Consultaion Appointment (Factory)");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Appointment At hospital (Factory)");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Database (Singeltone)");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 76, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(265, 265, 265))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(91, 91, 91)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(74, 74, 74))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))
                .addGap(114, 114, 114))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        notivication();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         try {
            Convert_Appointment();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Hospital_Services_Application_facade.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            OnlineConsultaionAppointment();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Hospital_Services_Application_facade.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            AppointmentAtHospitalINFO();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Hospital_Services_Application_facade.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            database_record();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Hospital_Services_Application_facade.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hospital_Services_Application_facade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hospital_Services_Application_facade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hospital_Services_Application_facade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hospital_Services_Application_facade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hospital_Services_Application_facade().setVisible(true);
                
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public static void database_record() throws FileNotFoundException {
       
        DB = Database.get_appointment_info();

        System.out.println("--------------Appointment At hospital INFO-------------");
        for (int i = 0; i < DB.size(); i++) {

            System.out.println(DB.get(i));
        }
        
        DB.clear();
        DB = Database.get_appointment_online();
        
        System.out.println("----------------Online consultation INFO------------");
        for (int i = 0; i < DB.size(); i++) {

            System.out.println(DB.get(i));
        }
        
        DB.clear();
        DB = Database.get_arabic_appointment_info();
        
        System.out.println("--------------تفاصيل المواعيد المتاحة في المستشفى-------------");
        for (int i = 0; i < DB.size(); i++) {

            System.out.println(DB.get(i));
        }
        
        DB.clear();
        DB = Database.get_arabic_appointment_online();
        
        System.out.println("----------------تفاصيل مواعيد الاستشارة عبر الإنترنت------------");
        for (int i = 0; i < DB.size(); i++) {

            System.out.println(DB.get(i));
        }
        
        DB.clear();
    }
    
    public static void notivication() {
        Notifications PatientaccNotifications = new Notifications();
        NotificationsScreen screen = new NotificationsScreen();
        screen.SetCommand(new TurnOnNotifications(PatientaccNotifications));
        screen.ClickOnNotifications();
    }
    
    public static void OnlineConsultaionAppointment() throws FileNotFoundException {
        Scanner rr = new Scanner(System.in);
        int appointmentID = -1;
        int cost = 0;
        DB = Database.get_appointment_online();
        
        System.out.println("----------------Online consultation INFO------------");
        for (int i = 0; i < DB.size(); i++) {

            System.out.println(DB.get(i));
        }

        System.out.println("---------------------------------------------------");

        do {

            System.out.print("select from the menu: ");
            appointmentID = rr.nextInt();

        } while (appointmentID < 0 || appointmentID > 2);

        System.out.print("Enter your total cost: ");
        cost = rr.nextInt();

        while (cost != 150) {

            System.out.println("payment method fail!! Try again.. ");
            System.out.print("Enter your total cost: ");
            cost = rr.nextInt();
        }
        BookingAnAppointment s1 = new BookingAnAppointment();
        Appointment a = s1.selection("Online Consultaion Appointment", appointmentID, cost);

        if (a instanceof OnlineConsultaionAppointment) {
            a.cost(cost);
            a.reservationInfo();
        }
        
        DB.clear();
    }
    
    public static void AppointmentAtHospitalINFO() throws FileNotFoundException {
        
        Scanner rr = new Scanner(System.in);
        int appointmentID = -1;
        int cost = 0;
        DB = Database.get_appointment_info();
        
        System.out.println("--------------Appointment At hospital INFO-------------");
        for (int i = 0; i < DB.size(); i++) {

            System.out.println(DB.get(i));
        }
        System.out.println("--------------------------------------------------------");

        do {

            System.out.print("select from the menu: ");
            appointmentID = rr.nextInt();

        } while (appointmentID < 0 || appointmentID > 2);

        System.out.print("Enter your total cost: ");
        cost = rr.nextInt();

        while (cost != 150) {

            System.out.println("payment method fail!! Try again.. ");
            System.out.print("Enter your total cost: ");
            cost = rr.nextInt();
        }
        BookingAnAppointment s1 = new BookingAnAppointment();
        Appointment a = s1.selection("Appointment At hospital", appointmentID, cost);

        if (a instanceof AppointmentAtHospital) {

            a.cost(cost);
            a.reservationInfo();
        }

        DB.clear();
    }
    
    public static void Convert_Appointment() throws FileNotFoundException {
        Scanner rr = new Scanner(System.in);
        String choice;
        int appointmentID = -1;
        int cost = 0;
        String second_choice = "";
        Convert_E_to_A translator = new Convert_E_to_A();
        second_choice = translator.Print_Arabic();

        do {

            System.out.print("اختر من القائمة: ");
            appointmentID = rr.nextInt();

        } while (appointmentID < 0 || appointmentID > 2);

        System.out.print("أدخل التكلفة الإجمالية: ");
        cost = rr.nextInt();

        while (cost != 150) {

            System.out.println("طريقة الدفع فشلت !! حاول مرة أخرى ...");
            System.out.print("أدخل التكلفة الإجمالية:");
            cost = rr.nextInt();
        }
        choice = second_choice;
        BookingAnAppointment s1 = new BookingAnAppointment();
        Appointment a = s1.selection(choice, appointmentID, cost);
        Appointment a2 = s1.selection(choice, appointmentID, cost);

        if (a instanceof OnlineConsultaionAppointment) {

            a.cost(cost);
            a.reservationInfo();
        } else if (a2 instanceof AppointmentAtHospital) {

            a2.cost(cost);
            a2.reservationInfo();
        }
    }
}